config/urls.py
from decorator_include import decorator_include
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.urls import path, reverse_lazy
from django.views.generic import RedirectView
from great_components.decorators import skip_ga360
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls
from wagtail_transfer import urls as wagtailtransfer_urls

import cms_extras.urls
import core.urls
import exportplan.urls
import sso.urls

urlpatterns = []

if settings.ENFORCE_STAFF_SSO_ENABLED:
    urlpatterns += [
        path('admin/login/', RedirectView.as_view(url=reverse_lazy('authbroker_client:login'), query_string=True)),
        path('auth/', include('authbroker_client.urls')),
    ]


urlpatterns += [
    path('django-admin/', decorator_include(skip_ga360, admin.site.urls)),
    path(
        # Has to come before main /admin/ else will fail
        'admin/wagtail-transfer/',
        decorator_include(skip_ga360, wagtailtransfer_urls),
    ),
    path('admin/cms-extras/', decorator_include(skip_ga360, cms_extras.urls, namespace='cms_extras')),
    path('admin/', decorator_include(skip_ga360, wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),  # NB: doesn't skip GA as we may analytics on this
    path('sso/', include(sso.urls)),
    path('', include(core.urls, namespace='core')),
    path('export-plan/', include(exportplan.urls)),
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path('', include(wagtail_urls)),
]


handler404 = 'core.views.handler404'

handler500 = 'core.views.handler500'

if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

exportplan/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, reverse_lazy
from great_components.decorators import skip_ga360

from exportplan import api, views

LOGIN_URL = reverse_lazy('core:login')

app_name = 'exportplan'

urlpatterns = [
    path(
        'section/marketing-approach/',
        login_required(views.ExportPlanMarketingApproachView.as_view(), login_url=LOGIN_URL),
        name='marketing-approach',
    ),
    path(
        'section/adaptation-for-your-target-market/',
        login_required(views.ExportPlanAdaptationForTargetMarketView.as_view(), login_url=LOGIN_URL),
        {'slug': 'adaptation-for-your-target-market'},
        name='adaptation-for-your-target-market',
    ),
    path(
        'section/about-your-business/',
        login_required(views.ExportPlanAboutYourBusinessView.as_view(), login_url=LOGIN_URL),
        {'slug': 'about-your-business'},
        name='about-your-business',
    ),
    path(
        'section/target-markets-research/',
        login_required(views.ExportPlanTargetMarketsResearchView.as_view(), login_url=LOGIN_URL),
        {'slug': 'target-markets-research'},
        name='target-markets-research',
    ),
    path(
        'section/business-objectives/',
        login_required(views.ExportPlanBusinessObjectivesView.as_view(), login_url=LOGIN_URL),
        {'slug': 'business-objectives'},
        name='business-objectives',
    ),
    path(
        'section/costs-and-pricing/',
        login_required(views.CostsAndPricingView.as_view(), login_url=LOGIN_URL),
        {'slug': 'costs-and-pricing'},
        name='costs-and-pricing',
    ),
    path(
        'section/getting-paid/',
        login_required(views.GettingPaidView.as_view(), login_url=LOGIN_URL),
        {'slug': 'getting-paid'},
        name='getting-paid',
    ),
    path(
        'section/funding-and-credit/',
        login_required(views.FundingAndCreditView.as_view(), login_url=LOGIN_URL),
        {'slug': 'funding-and-credit'},
        name='funding-and-credit',
    ),
    path(
        'section/travel-and-business-policies/',
        login_required(views.TravelBusinessPoliciesView.as_view(), login_url=LOGIN_URL),
        {'slug': 'travel-and-business-policies'},
        name='travel-and-business-policies',
    ),
    path(
        'section/<slug:slug>/',
        login_required(views.ExportPlanSectionView.as_view(), login_url=LOGIN_URL),
        name='section',
    ),
    path('logo', login_required(views.LogoFormView.as_view(), login_url=LOGIN_URL), name='add-logo'),
    path(
        'service-page/', login_required(views.ExportPlanServicePage.as_view(), login_url=LOGIN_URL), name='service-page'
    ),
    path(
        'api/recommended-countries/',
        login_required(skip_ga360(api.ExportPlanRecommendedCountriesDataView.as_view()), login_url=LOGIN_URL),
        name='ajax-recommended-countries-data',
    ),
    path('api/export-plan/', skip_ga360(api.UpdateExportPlanAPIView.as_view()), name='api-update-export-plan'),
    path(
        'api/remove-country-data/',
        skip_ga360(api.ExportPlanRemoveCountryDataView.as_view()),
        name='api-remove-country-data',
    ),
    path('api/remove-sector/', skip_ga360(api.ExportPlanRemoveSectorView.as_view()), name='api-remove-sector'),
    path('api/country-data/', skip_ga360(api.ExportPlanCountryDataView.as_view()), name='api-country-data'),
    path(
        'api/population-data-by-country/',
        skip_ga360(api.ExportPlanPopulationDataByCountryView.as_view()),
        name='api-population-data-by-country',
    ),
    path(
        'api/target-age-country-population-data/',
        skip_ga360(api.TargetAgeCountryPopulationData.as_view()),
        name='api-target-age-country-population-data',
    ),
    path(
        'api/society-data-by-country/',
        skip_ga360(api.ExportPlanSocietyDataByCountryView.as_view()),
        name='api-society-data-by-country',
    ),
    path(
        'api/calculate-cost-and-pricing/',
        skip_ga360(api.UpdateCalculateCostAndPricingAPIView.as_view()),
        name='api-calculate-cost-and-pricing',
    ),
    path('api/objectives/create/', skip_ga360(api.ObjectivesCreateAPIView.as_view()), name='api-objectives-create'),
    path('api/objectives/update/', skip_ga360(api.ObjectivesUpdateAPIView.as_view()), name='api-objectives-update'),
    path('api/objectives/delete/', skip_ga360(api.ObjectivesDestroyAPIView.as_view()), name='api-objectives-delete'),
    path(
        'api/model-object/manage/', skip_ga360(api.ModelObjectManageAPIView.as_view()), name='api-model-object-manage'
    ),
    path(
        'api/route-to-markets/create/',
        skip_ga360(api.RouteToMarketsCreateAPIView.as_view()),
        name='api-route-to-markets-create',
    ),
    path(
        'api/route-to-markets/update/',
        skip_ga360(api.RouteToMarketsUpdateAPIView.as_view()),
        name='api-route-to-markets-update',
    ),
    path(
        'api/route-to-markets/delete/',
        skip_ga360(api.RouteToMarketsDestroyAPIView.as_view()),
        name='api-route-to-markets-delete',
    ),
    path(
        'api/target-markets-documents/create/',
        skip_ga360(api.TargetMarketDocumentsCreateAPIView.as_view()),
        name='api-target-markets-documents-create',
    ),
    path(
        'api/target-markets-documents/update/',
        skip_ga360(api.TargetMarketDocumentUpdateAPIView.as_view()),
        name='api-target-markets-documents-update',
    ),
    path(
        'api/target-markets-documents/delete/',
        skip_ga360(api.TargetMarketDocumentsDestroyAPIView.as_view()),
        name='api-target-markets-documents-delete',
    ),
    path(
        'api/funding-credit-options/create/',
        skip_ga360(api.FundingCreditOptionsCreateAPIView.as_view()),
        name='api-funding-credit-options-create',
    ),
    path(
        'api/funding-credit-options/update/',
        skip_ga360(api.FundingCreditOptionsUpdateAPIView.as_view()),
        name='api-funding-credit-options-update',
    ),
    path(
        'api/funding-credit-options/delete/',
        skip_ga360(api.FundingCreditOptionsDestroyAPIView.as_view()),
        name='api-funding-credit-options-delete',
    ),
]

sso/urls.py
from django.urls import path
from great_components.decorators import skip_ga360

from sso.api import LessonCompletedAPIView
from sso.views import (
    SSOBusinessUserCreateView,
    SSOBusinessUserLoginView,
    SSOBusinessUserLogoutView,
    SSOBusinessVerifyCodeView,
)

app_name = 'sso'


urlpatterns = [
    path('api/business-login/', skip_ga360(SSOBusinessUserLoginView.as_view()), name='business-sso-login-api'),
    path('api/business-logout/', skip_ga360(SSOBusinessUserLogoutView.as_view()), name='business-sso-logout-api'),
    path(
        'api/business-user-create/',
        skip_ga360(SSOBusinessUserCreateView.as_view()),
        name='business-sso-create-user-api',
    ),
    path(
        'api/business-verify-code/',
        skip_ga360(SSOBusinessVerifyCodeView.as_view()),
        name='business-sso-verify-code-api',
    ),
    path(
        'api/v1/lesson-completed/<int:lesson>/', skip_ga360(LessonCompletedAPIView.as_view()), name='lesson-completed'
    ),
]

exportplan/models.py
from django.conf import settings
from great_components.mixins import GA360Mixin
from wagtail.core.models import Page

from core import cms_slugs, mixins


class ExportPlanDashboardPage(
    mixins.AuthenticatedUserRequired,
    mixins.WagtailAdminExclusivePageMixin,
    mixins.EnableTourMixin,
    mixins.ExportPlanMixin,
    mixins.WagtailGA360Mixin,
    GA360Mixin,
    Page,
):

    template = 'exportplan/dashboard_page.html'

    def get_context(self, request):
        request.user.set_page_view(cms_slugs.EXPORT_PLAN_DASHBOARD_URL)
        context = super().get_context(request)
        context['sections'] = request.user.export_plan.build_export_plan_sections()
        context['export_plan_progress'] = request.user.export_plan.calculate_ep_progress()

        self.set_ga360_payload(
            page_id=self.id,
            business_unit=settings.GA360_BUSINESS_UNIT,
            site_section=str(self.url or '/').split('/')[1],
        )
        self.add_ga360_data_to_payload(request)
        context['ga360'] = self.ga360_payload

        return context

exportplan/templates/exportplan/automated_list_page.html
{% extends "core/base.html" %}

{% load pageurl from wagtailcore_tags %}

{% block content %}
  <section>
    <div class="container">
      Go to <a href="/export-plan/dashboard/">your dashboard</a>.
      <h1 class="h-l m-t-xl" id="topic-title">{{ page.title }}</h1>
      {% include 'core/personalised_body.html' %}
    </div>
  </section>
{% endblock %}

exportplan/templates/exportplan/builder_landing_page.html
{% extends "core/base.html" %}

{% load great_components %}

{% block css_layout_class %}export-plan-builder{% endblock %}

{% block content %}

{% include "exportplan/includes/sticky-header.html" %}

<section class="bg-stone-30 p-v-m">
  <div class="container">
    <div class="grid">

      <aside class="completion-status c-1-4">
        <img src="https://via.placeholder.com/200/dfd5c5?text=Company logo" alt="" class="w-full">
        <h2 class="h-s">Export plan</h2>
        <p class="text-mid-grey" id="exportplan-completion-progress-indicator">20% completed</p>
        <h2 class="h-s m-b-s" id="exportplan-continue-leaning-title">Continue learning</h2>
        {% card title='Calculate consumer demand' subheading='Market research' url='#' %}
      </aside>

      <div class="section-list c-3-4" id="section-list">
        <div class="flex-grid">
          {% for section in sections %}
          <div class="c-1-3">
            <div class="bg-white m-b-s exportplan-section-item">
              {% if forloop.first %}
              <a class="w-full" href="{% url 'exportplan:about-your-business' %}">
              {% else %}
              <a class="w-full" href="#">
              {% endif %}
                <img class="w-full" src="https://via.placeholder.com/160x90/dfd5c5?text=Preview image" alt="">
                <div class="p-h-s p-b-s">
                  <h3 class="h-s">{{ section }}</h3>
                </div>
              </a>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}


{% block body_js %}
    <script type="text/javascript">
        var element = document.createElement('div');
        document.body.appendChild(element);
        ditMVP.Tour({element: element, isOpenModal: true})
    </script>
{% endblock %}

exportplan/templates/exportplan/dashboard.html
{% extends "core/base.html" %}

{% load great_components %}

{% block css_layout_class %}export-plan-dashboard{% endblock %}

{% block content %}

{% include "exportplan/includes/sticky-header.html" %}

<section class="bg-stone-30 p-v-m">
  <div class="container">
    <div class="grid">

      <aside class="completion-status c-1-4">
        <img src="https://via.placeholder.com/200/dfd5c5?text=Company logo" alt="" class="w-full">
        <h2 class="h-s">Export plan</h2>
        <p class="text-mid-grey" id="exportplan-completion-progress-indicator">20% completed</p>
        <h2 class="h-s m-b-s" id="exportplan-continue-leaning-title">Continue learning</h2>
        {% card title='Calculate consumer demand' subheading='Market research' url='#' %}
      </aside>

      <div class="section-list c-3-4" id="section-list">
        <div class="flex-grid">
          {% for section in sections %}
          <div class="c-1-3">
            <div class="bg-white m-b-s exportplan-section-item">
              {% if section == 'Target markets' %}
              <a class="w-full" href="{% url 'exportplan:target-markets' %}" id="{{ section.title|slugify }}">
              {% else %}
              <a class="w-full" href="#" id="{{ section.title|slugify }}">
              {% endif %}
                <img class="w-full" src="https://via.placeholder.com/160x90/dfd5c5?text=Preview image" alt="">
                <div class="p-h-s p-b-s">
                  <h3 class="h-s">{{ section }}</h3>
                </div>
              </a>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

exportplan/templates/exportplan/dashboard_page.html
{% extends "core/base.html" %}

{% load to_json %}

{% load static from staticfiles %}

{% load great_components %}

{% block css_layout_class %}export-plan-dashboard{% endblock %}

{% block content %}

<section class="export-plan-dashboard__section bg-blue-deep-10">
  <aside class="export-plan-dashboard__sidebar p-v-m p-r-s p-f-s text-center bg-white">
    {% if not request.user.company.logo %}
    <a id="add-image" href="{% url 'exportplan:add-logo' %}"
      class="link text-center text-blue-deep-80 p-t-xs p-b-s section-upload">
      <i class="fas fa-upload"></i>
      <h3 class="m-v-xs bold">Upload your logo</h3>
      <p class="m-0">Click here.</p>
      <p class="m-0">PNG or JPG, 270x170 pixels</p>
    </a>
    {% else %}
    <img alt="{{ request.user.company.name }}" src="{{ request.user.company.logo }}" class="w-full" />
    <a id="edit-image" href="{% url 'exportplan:add-logo' %}" class="link pencil-link">Edit</a>
    {% endif %}
    <div id="buttons-disabled" class="m-t-m">
      <button class="button button--secondary button--full-width button--icon m-b-xs" disabled="disabled">
        <i class="fas fa-download"></i>
        <span class="body-m text-white">Save your plan as a PDF</span>
      </button>
    </div>
  </aside>
  <div class="export-plan-dashboard__container container">
    <div id="section-progress">
      <div class="m-h-s m-t-m">
        <div class="progress-bar progress-bar--white-track">
          <span style="width: {% widthratio export_plan_progress.export_plan_progress.sections_completed export_plan_progress.export_plan_progress.sections_total 100 %}%"></span>
        </div>
        <p class="body-m-b m-t-xxs m-b-0">{{ export_plan_progress.export_plan_progress.sections_completed }} out of {{ export_plan_progress.export_plan_progress.sections_total }} export plan sections complete</p>
      </div>
    </div>
    <div class="section-list p-v-m p-h-s" id="section-list">
      <div class="media media--middle m-b-l">
        <div class="media__figure">
          <i class="fas fa-info-circle fa-lg text-blue-deep-90"></i>
        </div>
        <div class="media__body">
          <div class="g-panel">
            <h3 class="h-xs text-blue-deep-80 p-t-xs">Some sections of Export Plan aren't available.</h3>
            <p class="text-blue-deep-80 m-t-xxs">This Beta is limited</p>
          </div>
        </div>
      </div>
      <div class="section-list__grid flex-grid" id="export-plan-dashboard">
        {% for section in sections %}
        <div class="c-1-3-xl c-1-2-m">
          <div class="section-list__item bg-white m-b-s">
            <a class="section-list__link w-1-1 link" href="{% url 'exportplan:section' slug=section.title|slugify %}"
              id="{{ section.title|slugify }}">
              <div class="bg-blue-deep-20 section-list__image-container">
                <img class="w-full p-h-s p-t-m p-b-s" src="{% static 'images/ep-placeholder.svg' %}"
                  alt="{{ section.title }}">
              </div>
              <div class="p-v-s p-h-xs">
                <h3 class="bold body-l-b text-blue-deep-80">{{ section.title }}</h3>
              </div>
            </a>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

</section>

{% endblock %}

{% block body_js %}
  {{ block.super }}
  <script type="text/javascript">
    var element = document.getElementById('export-plan-dashboard');
    magna.createDashboard({
      element: element,
      sections: {{ sections|to_json}},
      export_plan_progress: {{ export_plan_progress|to_json }},
    })

    var buttonsDisabled = document.getElementById('buttons-disabled');
    magna.createDisabledButton({
      element: buttonsDisabled,
    })
  </script>
{% endblock %}

exportplan/templates/exportplan/export_plan_page.html
{% extends "core/base.html" %}

{% load pageurl from wagtailcore_tags %}

{% block content %}
  <section>
    <div class="container">
      Go to <a href="/export-plan/dashboard/">your dashboard</a>.
      <h1 class="h-l m-t-xl" id="topic-title">{{ page.title }}</h1>
      {% include 'core/personalised_body.html' %}
    </div>
  </section>
{% endblock %}

exportplan/templates/exportplan/landing_page.html
{% extends "core/base.html" %}

{% load pageurl from wagtailcore_tags %}

{% block content %}
  <section>
    <div class="container">
      Go to <a href="{% url 'exportplan:dashboard' %}">your dashboard</a>.
    </div>
  </section>
{% endblock %}

exportplan/templates/exportplan/logo-form.html
{% extends "core/base.html" %}

{% load pageurl from wagtailcore_tags %}

{% block content %}
    <div class="container">
       <div class="grid-row">
            <div class="column-one-half">
                {% block form_contents %}
                    <form method="post" class="m-t-m" enctype="multipart/form-data">
                        {% block form %}
                        {% csrf_token %}
                          {{ form }}
                        {% endblock %}
                        {% block form_button %}
                            <button class="button m-v-s">Save and continue</button>
                        {% endblock %}
                     </form>
                {% endblock %}
                {% block back_link %}
                    <a class="link" href="/export-plan/dashboard/">Back</a>
                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

exportplan/templates/exportplan/section.html
{% extends "core/base.html" %}
{% load static %}
{% load to_json %}

{% block css_layout_class %}export-plan{% endblock %}

{% block content %}

{% block sidebar %}{% include "exportplan/includes/sidebar.html" %}{% endblock %}

<div class="main-section {% block mainclasses %}bg-white text-blue-deep-80 {% endblock %} {{ view.slug }}-content" id="{{ view.slug }}-content">

  <section class="section--intro bg-blue-deep-90">
    <div class="container">
      <div class="grid">
        <div class="c-1-4-l">&nbsp;</div>
        <div class="c-2-3-m c-1-2-xl p-t-xl p-b-s text-white">
          {% block intro_content %}{% endblock %}
          <h1 class="h-l text-red-80">{% block intro_title %}{% endblock %}</h1>
          <p>{% block intro_description %}{% endblock %}</p>
        </div>
        <div class="c-1-12-m c-1-4-xl">&nbsp;</div>
        <img src={% block banner_image %}{% static 'images/ep-placeholder.svg' %}{% endblock %} alt="" class="section--intro-image m-r-auto m-f-auto" />
      </div>
    </div>
  </section>

  <section class="container">
    <div class="grid">
      <div class="c-1-4-l">&nbsp;</div>
      <div class="c-2-3-m c-1-2-xl">
        {% block main_content %}{% endblock %}
      </div>
      <div class="c-1-12-m c-1-4-xl">&nbsp;</div>
    </div>
  </section>

  {% block user_input %}{% endblock %}

  {% block additional_content %}{% endblock %}

  {% block next_section %}
  <section class="p-v-m bg-blue-deep-80">
    <div class="container">
      <div class="grid">
        <div class="c-1-4-l">&nbsp;</div>
        <div class="c-2-3-m c-1-2-xl">
          {% block section_complete %}{% include "exportplan/includes/section_complete.html" %}{% endblock %}
          {% if next_section and not next_section.disabled %}
            <p class="h-xs m-b-0 text-white">Next</p>
            <a class="text-red-80 link" href="{{ next_section.url }}" title="{{ next_section.title }}"><span class="inline-block h-l text-red-80 link--underline p-0 m-b-xs">{{ next_section.title }}</span> <br /><i class="fas fa-arrow-circle-right text-red-80"></i> </a>
          {% endif %}
          {% block back_button %}
            <div class="m-t-l"><a class="button button--tertiary button--icon" href="/export-plan/dashboard/" title="Back to Export Plan home"><i class="fas fa-arrow-left"></i> Back to Export Plan home</a></div>
          {% endblock %}
        </div>
        <div class="c-1-12-m c-1-4-xl">&nbsp;</div>
      </div>
    </div>
  </section>
  {% endblock %}
</div>
{% endblock %}

exportplan/templates/exportplan/service_page.html
{% extends 'exportplan/section.html' %}

{% block intro_content %}
<h1 class="h-xl">Service Page</h1>
<p>This feature is coming soon...</p>
{% endblock %}