config/urls.py
from decorator_include import decorator_include
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.urls import path, reverse_lazy
from django.views.generic import RedirectView
from great_components.decorators import skip_ga360
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls
from wagtail_transfer import urls as wagtailtransfer_urls

import cms_extras.urls
import core.urls
import exportplan.urls
import sso.urls

urlpatterns = []

if settings.ENFORCE_STAFF_SSO_ENABLED:
    urlpatterns += [
        path('admin/login/', RedirectView.as_view(url=reverse_lazy('authbroker_client:login'), query_string=True)),
        path('auth/', include('authbroker_client.urls')),
    ]


urlpatterns += [
    path('django-admin/', decorator_include(skip_ga360, admin.site.urls)),
    path(
        # Has to come before main /admin/ else will fail
        'admin/wagtail-transfer/',
        decorator_include(skip_ga360, wagtailtransfer_urls),
    ),
    path('admin/cms-extras/', decorator_include(skip_ga360, cms_extras.urls, namespace='cms_extras')),
    path('admin/', decorator_include(skip_ga360, wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),  # NB: doesn't skip GA as we may analytics on this
    path('sso/', include(sso.urls)),
    path('', include(core.urls, namespace='core')),
    path('export-plan/', include(exportplan.urls)),
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path('', include(wagtail_urls)),
]


handler404 = 'core.views.handler404'

handler500 = 'core.views.handler500'

if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

core/urls.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.urls import path, reverse_lazy
from great_components.decorators import skip_ga360

from core import cms_slugs, views, views_api

app_name = 'core'

LOGIN_URL = reverse_lazy('core:login')


def anonymous_user_required(function):
    inner = user_passes_test(
        lambda user: bool(user.is_anonymous),
        # redirect if the user DOES NOT pass the test
        cms_slugs.DASHBOARD_URL,
        None,
    )
    return inner(function)


urlpatterns = [
    path(
        'where-to-export/',
        login_required(views.CompareCountriesView.as_view(), login_url=LOGIN_URL),
        name='compare-countries',
    ),
    path(
        'capability/<str:topic>/<str:chapter>/<str:article>/',
        login_required(views.ArticleView.as_view(), login_url=LOGIN_URL),
        name='capability-article',
    ),
    path('login/', anonymous_user_required(views.LoginView.as_view()), name='login'),
    path('signup/', anonymous_user_required(views.SignupView.as_view()), name='signup'),
    path(
        'signup/company-name/',
        login_required(skip_ga360(views.CompanyNameFormView.as_view())),
        name='set-company-name',
    ),
    path(
        'signup/tailored-content/<str:step>/',
        anonymous_user_required(
            skip_ga360(views.SignupForTailoredContentWizardView.as_view(url_name='core:signup-wizard-tailored-content'))
        ),
        name='signup-wizard-tailored-content',
    ),
    path(
        'signup/export-plan/<str:step>/',
        login_required(
            skip_ga360(views.SignupForExportPlanWizardView.as_view(url_name='core:signup-wizard-export-plan'))
        ),
        name='signup-wizard-export-plan',
    ),
    path('contact-us/help/', skip_ga360(views.ContactUsHelpFormView.as_view()), name='contact-us-help'),
    path('contact-us/success/', skip_ga360(views.ContactUsHelpSuccessView.as_view()), name='contact-us-success'),
    path('api/update-company/', skip_ga360(views_api.UpdateCompanyAPIView.as_view()), name='api-update-company'),
    path('api/lookup-product/', skip_ga360(views_api.ProductLookupView.as_view()), name='api-lookup-product'),
    path(
        'api/lookup-product-schedule/',
        skip_ga360(views_api.ProductLookupScheduleView.as_view()),
        name='api-lookup-product-schedule',
    ),
    path('api/countries/', skip_ga360(views_api.CountriesView.as_view()), name='api-countries'),
    path(
        'api/suggested-countries/',
        skip_ga360(views_api.SuggestedCountriesView.as_view()),
        name='api-suggested-countries',
    ),
    path('api/create-token/', skip_ga360(views_api.CreateTokenView.as_view()), name='api-create-token'),
    path('api/check/', skip_ga360(views_api.CheckView.as_view()), name='api-check'),
    path('api/data-service/comtrade/', skip_ga360(views_api.ComTradeDataView.as_view()), name='api-comtrade-data'),
    path('api/data-service/countrydata/', skip_ga360(views_api.CountryDataView.as_view()), name='api-country-data'),
]

exportplan/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, reverse_lazy
from great_components.decorators import skip_ga360

from exportplan import api, views

LOGIN_URL = reverse_lazy('core:login')

app_name = 'exportplan'

urlpatterns = [
    path(
        'section/marketing-approach/',
        login_required(views.ExportPlanMarketingApproachView.as_view(), login_url=LOGIN_URL),
        name='marketing-approach',
    ),
    path(
        'section/adaptation-for-your-target-market/',
        login_required(views.ExportPlanAdaptationForTargetMarketView.as_view(), login_url=LOGIN_URL),
        {'slug': 'adaptation-for-your-target-market'},
        name='adaptation-for-your-target-market',
    ),
    path(
        'section/about-your-business/',
        login_required(views.ExportPlanAboutYourBusinessView.as_view(), login_url=LOGIN_URL),
        {'slug': 'about-your-business'},
        name='about-your-business',
    ),
    path(
        'section/target-markets-research/',
        login_required(views.ExportPlanTargetMarketsResearchView.as_view(), login_url=LOGIN_URL),
        {'slug': 'target-markets-research'},
        name='target-markets-research',
    ),
    path(
        'section/business-objectives/',
        login_required(views.ExportPlanBusinessObjectivesView.as_view(), login_url=LOGIN_URL),
        {'slug': 'business-objectives'},
        name='business-objectives',
    ),
    path(
        'section/costs-and-pricing/',
        login_required(views.CostsAndPricingView.as_view(), login_url=LOGIN_URL),
        {'slug': 'costs-and-pricing'},
        name='costs-and-pricing',
    ),
    path(
        'section/getting-paid/',
        login_required(views.GettingPaidView.as_view(), login_url=LOGIN_URL),
        {'slug': 'getting-paid'},
        name='getting-paid',
    ),
    path(
        'section/funding-and-credit/',
        login_required(views.FundingAndCreditView.as_view(), login_url=LOGIN_URL),
        {'slug': 'funding-and-credit'},
        name='funding-and-credit',
    ),
    path(
        'section/travel-and-business-policies/',
        login_required(views.TravelBusinessPoliciesView.as_view(), login_url=LOGIN_URL),
        {'slug': 'travel-and-business-policies'},
        name='travel-and-business-policies',
    ),
    path(
        'section/<slug:slug>/',
        login_required(views.ExportPlanSectionView.as_view(), login_url=LOGIN_URL),
        name='section',
    ),
    path('logo', login_required(views.LogoFormView.as_view(), login_url=LOGIN_URL), name='add-logo'),
    path(
        'service-page/', login_required(views.ExportPlanServicePage.as_view(), login_url=LOGIN_URL), name='service-page'
    ),
    path(
        'api/recommended-countries/',
        login_required(skip_ga360(api.ExportPlanRecommendedCountriesDataView.as_view()), login_url=LOGIN_URL),
        name='ajax-recommended-countries-data',
    ),
    path('api/export-plan/', skip_ga360(api.UpdateExportPlanAPIView.as_view()), name='api-update-export-plan'),
    path(
        'api/remove-country-data/',
        skip_ga360(api.ExportPlanRemoveCountryDataView.as_view()),
        name='api-remove-country-data',
    ),
    path('api/remove-sector/', skip_ga360(api.ExportPlanRemoveSectorView.as_view()), name='api-remove-sector'),
    path('api/country-data/', skip_ga360(api.ExportPlanCountryDataView.as_view()), name='api-country-data'),
    path(
        'api/population-data-by-country/',
        skip_ga360(api.ExportPlanPopulationDataByCountryView.as_view()),
        name='api-population-data-by-country',
    ),
    path(
        'api/target-age-country-population-data/',
        skip_ga360(api.TargetAgeCountryPopulationData.as_view()),
        name='api-target-age-country-population-data',
    ),
    path(
        'api/society-data-by-country/',
        skip_ga360(api.ExportPlanSocietyDataByCountryView.as_view()),
        name='api-society-data-by-country',
    ),
    path(
        'api/calculate-cost-and-pricing/',
        skip_ga360(api.UpdateCalculateCostAndPricingAPIView.as_view()),
        name='api-calculate-cost-and-pricing',
    ),
    path('api/objectives/create/', skip_ga360(api.ObjectivesCreateAPIView.as_view()), name='api-objectives-create'),
    path('api/objectives/update/', skip_ga360(api.ObjectivesUpdateAPIView.as_view()), name='api-objectives-update'),
    path('api/objectives/delete/', skip_ga360(api.ObjectivesDestroyAPIView.as_view()), name='api-objectives-delete'),
    path(
        'api/model-object/manage/', skip_ga360(api.ModelObjectManageAPIView.as_view()), name='api-model-object-manage'
    ),
    path(
        'api/route-to-markets/create/',
        skip_ga360(api.RouteToMarketsCreateAPIView.as_view()),
        name='api-route-to-markets-create',
    ),
    path(
        'api/route-to-markets/update/',
        skip_ga360(api.RouteToMarketsUpdateAPIView.as_view()),
        name='api-route-to-markets-update',
    ),
    path(
        'api/route-to-markets/delete/',
        skip_ga360(api.RouteToMarketsDestroyAPIView.as_view()),
        name='api-route-to-markets-delete',
    ),
    path(
        'api/target-markets-documents/create/',
        skip_ga360(api.TargetMarketDocumentsCreateAPIView.as_view()),
        name='api-target-markets-documents-create',
    ),
    path(
        'api/target-markets-documents/update/',
        skip_ga360(api.TargetMarketDocumentUpdateAPIView.as_view()),
        name='api-target-markets-documents-update',
    ),
    path(
        'api/target-markets-documents/delete/',
        skip_ga360(api.TargetMarketDocumentsDestroyAPIView.as_view()),
        name='api-target-markets-documents-delete',
    ),
    path(
        'api/funding-credit-options/create/',
        skip_ga360(api.FundingCreditOptionsCreateAPIView.as_view()),
        name='api-funding-credit-options-create',
    ),
    path(
        'api/funding-credit-options/update/',
        skip_ga360(api.FundingCreditOptionsUpdateAPIView.as_view()),
        name='api-funding-credit-options-update',
    ),
    path(
        'api/funding-credit-options/delete/',
        skip_ga360(api.FundingCreditOptionsDestroyAPIView.as_view()),
        name='api-funding-credit-options-delete',
    ),
]

sso/urls.py
from django.urls import path
from great_components.decorators import skip_ga360

from sso.api import LessonCompletedAPIView
from sso.views import (
    SSOBusinessUserCreateView,
    SSOBusinessUserLoginView,
    SSOBusinessUserLogoutView,
    SSOBusinessVerifyCodeView,
)

app_name = 'sso'


urlpatterns = [
    path('api/business-login/', skip_ga360(SSOBusinessUserLoginView.as_view()), name='business-sso-login-api'),
    path('api/business-logout/', skip_ga360(SSOBusinessUserLogoutView.as_view()), name='business-sso-logout-api'),
    path(
        'api/business-user-create/',
        skip_ga360(SSOBusinessUserCreateView.as_view()),
        name='business-sso-create-user-api',
    ),
    path(
        'api/business-verify-code/',
        skip_ga360(SSOBusinessVerifyCodeView.as_view()),
        name='business-sso-verify-code-api',
    ),
    path(
        'api/v1/lesson-completed/<int:lesson>/', skip_ga360(LessonCompletedAPIView.as_view()), name='lesson-completed'
    ),
]

core/forms.py
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV3
from directory_forms_api_client.forms import GovNotifyEmailActionMixin
from django.forms import Textarea
from django.utils.html import mark_safe
from great_components import forms

from core.cms_slugs import TERMS_URL


def build_checkbox(label):
    return forms.BooleanField(
        label=label, required=False, widget=forms.CheckboxWithInlineLabel(attrs={'disabled': True})
    )


class ExportPlanForm(forms.Form):

    step_a = build_checkbox('About your business')
    step_b = build_checkbox('Objectives')
    step_c = build_checkbox('Target Markets')
    step_d = build_checkbox('Adaptation for international markets')
    step_e = build_checkbox('Marketing approach')
    step_f = build_checkbox('Costs and pricing')
    step_g = build_checkbox('Finances')
    step_h = build_checkbox('Payment Methods and when to get paid')
    step_i = build_checkbox('Travel and business policies')
    step_j = build_checkbox('Busines risk')
    step_k = build_checkbox('Action plan')


class NoOperationForm(forms.Form):
    pass


class WhatAreYouSellingForm(forms.Form):
    PRODUCTS = 'PRODUCTS'
    SERVICES = 'SERVICES'
    PRODUCTS_AND_SERVICES = 'PRODUCTS_AND_SERVICES'
    CHOICES = (
        (PRODUCTS, 'Products'),
        (SERVICES, 'Services'),
        (PRODUCTS_AND_SERVICES, 'Products and Services'),
    )
    choice = forms.ChoiceField(
        label='',
        widget=forms.RadioSelect(),
        choices=CHOICES,
    )


TERMS_LABEL = mark_safe(
    'Tick this box to accept the '
    f'<a href="{TERMS_URL}" target="_blank">terms and '
    'conditions</a> of the great.gov.uk service.'
)


class ContactUsHelpForm(GovNotifyEmailActionMixin, forms.Form):
    comment = forms.CharField(
        label='Please give us as much detail as you can',
        widget=Textarea,
    )
    given_name = forms.CharField(label='First name')
    family_name = forms.CharField(label='Last name')
    email = forms.EmailField()
    captcha = ReCaptchaField(label='', label_suffix='', widget=ReCaptchaV3())
    terms_agreed = forms.BooleanField(label=TERMS_LABEL)


class ProductSearchForm(forms.Form):
    products = forms.CharField()


class CompanyNameForm(forms.Form):
    name = forms.CharField()

core/templates/core/article.html
{% extends 'core/base.html' %}
{% load breadcrumbs from great_components %}
{% load url_map %}

{% block content %}
    <div id="great-hero" class="container p-s">
        <h2 class="h-m">Welcome {{ request.user.first_name|default:request.user.email }}</h2>
        {% breadcrumbs article_name %}
          <a href="{% url_map 'dashboard' %}" id="breadcrumbs-dashboard">Home</a>
          <a href="http://www.example.com" id="breadcrumbs-{{ topic_name|slugify }}">{{ topic_name }}</a>
          <a href="http://www.example.com" id="breadcrumbs-{{ chapter_name|slugify }}">{{ chapter_name }}</a>
        {% endbreadcrumbs %}
    </div>

    <div class="container">
        <div class="grid m-b-s">
            <div class="c-full">
                {% if not is_read %}
                    <form class="bg-white p-s great-mvp-success-card" method="post" id="form-mark-as-read">
                        {% csrf_token %}
                        <h3 class="h-l pb-xxs w-1-2">{{ article_name|title }}</h3>
                        <p class="m-b-0 ">{% lorem 5 p %}</p>
                        <button class="g-button" id="mark-as-read">Mark as read</button>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

{% block body_js %}
    {{ block.super }}
    <script type="text/javascript">
        var element = document.createElement('div');
        document.body.appendChild(element);

        var isOpen = {% if request.user.company.expertise_countries_label %}false{%else %}true{% endif %};
        magna.CountriesModal({
            element: element,
            isOpen: isOpen
        });
    </script>
{% endblock %}

core/templates/core/base.html
{% extends 'great_components/base.html' %}
{% load static %}
{% load static_absolute from great_components %}
{% load url_map %}
{% load to_json %}

{% block head_title %}
  {% if page.title %}
    {{ page.title }} | great.gov.uk
  {% else %}
    Welcome to great.gov.uk
  {% endif %}
{% endblock %}

{% block head_css %}
    <link href="{% static 'styles.css' %}" media="all" rel="stylesheet" />
{% endblock %}

{% block head_js %}
  {{ block.super }}
    <script type="text/javascript" src="{% static 'magna.js' %}"></script>

    <script type="text/javascript">
      var product = '{{ request.user.export_plan.data.export_commodity_codes.0.commodity_code }}';
      var country = '{{ request.user.export_plan.data.export_countries.0.country_name }}';
      var dataLayer = window.dataLayer || []
      dataLayer.push({
        'productAdded': product || "False",
        'marketAdded': country || "False",
      });
       // static values that will not be updated by user interacting with react components
      magna.setConfig({
          apiLoginUrl: '{% url "sso:business-sso-login-api" %}',
          apiLogoutUrl: '{% url "sso:business-sso-logout-api" %}',
          apiLookupProductUrl: '{% url "core:api-lookup-product" %}',
          apiLookupProductScheduleUrl: '{% url "core:api-lookup-product-schedule" %}',
          apiCountriesUrl: '{% url "core:api-countries" %}',
          apiSuggestedCountriesUrl: '{% url "core:api-suggested-countries" %}',
          apiSignupUrl: '{% url "sso:business-sso-create-user-api" %}',
          apiUpdateCompanyUrl:  '{% url "core:api-update-company" %}',
          apiUpdateExportPlanUrl: '{% url "exportplan:api-update-export-plan" %}',
          apiObjectivesUpdateUrl: '{% url "exportplan:api-objectives-update" %}',
          apiObjectivesCreateUrl: '{% url "exportplan:api-objectives-create" %}',
          apiObjectivesDeleteUrl: '{% url "exportplan:api-objectives-delete" %}',
          apiRouteToMarketCreateUrl: '{% url "exportplan:api-route-to-markets-create" %}',
          apiRouteToMarketUpdateUrl: '{% url "exportplan:api-route-to-markets-update" %}',
          apiRouteToMarketDeleteUrl: '{% url "exportplan:api-route-to-markets-delete" %}',
          apiTargetMarketDocumentsCreateUrl: '{% url "exportplan:api-target-markets-documents-create" %}',
          apiTargetMarketDocumentsUpdateUrl: '{% url "exportplan:api-target-markets-documents-update" %}',
          apiTargetMarketDocumentsDeleteUrl: '{% url "exportplan:api-target-markets-documents-delete" %}',
          apiFundingCreditOptionsCreateUrl: '{% url "exportplan:api-funding-credit-options-create" %}',
          apiFundingCreditOptionsUpdateUrl: '{% url "exportplan:api-funding-credit-options-update" %}',
          apiFundingCreditOptionsDeleteUrl: '{% url "exportplan:api-funding-credit-options-delete" %}',
          countriesBySectorsDataUrl: '{% url "exportplan:ajax-recommended-countries-data" %}',
          apiComTradeDataUrl: '{% url "core:api-comtrade-data" %}',
          apiCountryDataUrl: '{% url "core:api-country-data" %}',
          removeSectorUrl: '{% url "exportplan:api-remove-sector" %}',
          countryAgeGroupDataUrl: '{% url "exportplan:api-target-age-country-population-data" %}',
          populationByCountryUrl: '{% url "exportplan:api-population-data-by-country" %}',
          updateCalculateCostAndPricing: '{% url "exportplan:api-calculate-cost-and-pricing" %}',
          societyByCountryUrl: '{% url "exportplan:api-society-data-by-country" %}',
          countryOptions: {{ javascript_components.country_choices|safe }},
          csrfToken: '{{ csrf_token }}',
          dashboardUrl: '{% url_map "dashboard" %}',
          googleUrl: '{{ javascript_components.google_url }}',
          industryOptions: {{ javascript_components.industry_options|safe }},
          linkedInUrl: '{{ javascript_components.linkedin_url }}',
          loginUrl: '{% url "core:login" %}{% if request.GET.next %}?next={{ request.GET.next }}{% endif %}',
          signupUrl: '{% url "core:signup" %}',
          passwordResetUrl: '{{ javascript_components.password_reset_url }}',
          removeCountryDataUrl: '{% url "exportplan:api-remove-country-data" %}',
          termsUrl: '{{ javascript_components.terms_url }}',
          user: {
            id: '{{ request.user.id }}',
            name: '{{ request.user.get_username }}',
            isAuthenticated: {{ request.user.is_authenticated|yesno:"true,false" }},
          },
          verifyCodeUrl: '{% url "sso:business-sso-verify-code-api" %}',
          refreshOnMarketChange: {% if no_refresh_on_market_change %}false{%else%}true{% endif %},
          urlCostsAndPricing: '{% url "exportplan:costs-and-pricing"%}'
      });
    </script>
{% endblock %}

{% block body_header %}
  {% include 'core/header.html' %}
  {% if request.user.is_authenticated %}
    {% include "core/includes/personalisation_bar.html" with profile=request.user.company %}
  {% elif FEATURE_ENABLE_PRODUCT_SEARCH_WHEN_NO_USER %}
    {% include "core/includes/personalisation_bar.html" %}
  {% endif %}
{% endblock %}

{% block body_content_container %}
  <main id="content" class="{% block css_layout_class %}{% endblock %}">
      {% block content_header %}{% endblock %}
      {% block content %}{% endblock %}
  </main>
{% endblock %}

{% block cookie_notice %}{% endblock %}

{% block body_footer %}
  {% include 'core/footer.html' %}
{% endblock %}

{% block body_js %}
    {{ block.super }}
    <script type="text/javascript">
      // dynamic value that can be updated by user interacting with react components
      magna.setInitialState({
        // prevents modals from opening on page load if user dismissed the modal already
        performSkipFeatureCookieCheck: true,
        nextUrl: '{% if request.GET.next %}{{ request.GET.next }}{% else %}{% url_map "dashboard" %}{% endif %}',
        modalIsOpen: {
          products: false,
          countries: false,
          industries: false,
          login: false,
          signup: false,
        },
        exportPlan:{
          products: {{request.user.export_plan.data.export_commodity_codes|to_json}},
          markets: {{request.user.export_plan.data.export_countries|to_json }}
        },
      })

      {% if tour %}
        var element = document.createElement('div');
        document.body.appendChild(element);
        magna.Tour({
          element: element,
          isOpenModal: true,
          steps: {{ tour.steps|safe }},
          title: '{{ tour.title }}',
          body: "{% autoescape off %}{{ tour.body }}{% endautoescape %}",
          buttonText: '{{ tour.button_text }}',
          disableTourCookieName: 'disable-tour-{{ page.content_type }}'
        })
    {% endif %}
  </script>
{% endblock %}

core/templates/core/compare_countries.html
{% extends "core/base.html" %}
{% load static %}
{% load wagtailcore_tags %}

{% block content %}
  <div id="where-to-export"">
      <section class="bg-white">
          <div class="container p-t-m p-b-m">
              <div class="grid">
                  <div class="c-1-2-l">
                      <div class="">
                          <h1 class="h-l p-b-0">{{ page.title }}</h1>
                          <div class="">
                            <p class="body-l">Exporting to the right place matters. This page helps you compare data for different places and make an informed choice.</p>
                          </div>
                          {% if data_tabs_enabled %}
                            <div id="cta-container"></div>
                          {% endif %}
                      </div>
                  </div>

                  <div class="c-1-2-l only-desktop">
                    <img src={% block banner_image %}{% static 'images/where-to-export.png' %}{% endblock %} alt="" class="max-width-80 m-r-auto m-f-auto" />
                  </div>
              </div>
          </div>
      </section>
  </div>
  {% if data_tabs_enabled %}
    <div class="hidden" id="next-steps">
      {% for component in dashboard_components %}
          {% if component.value.route_type == 'learn' or component.value.route_type == 'plan' %}
              <article class="dashboard__routing-block c-1-2 wide">
                  {% include_block component with wide=True %}
              </article>
          {% endif %}
      {% endfor %}
    </div>

    <div id="open-product-finder" class="m-v-l"
      data-productname="{{ request.user.export_plan.data.export_commodity_codes.0.commodity_name }}"
      data-productcode="{{ request.user.export_plan.data.export_commodity_codes.0.commodity_code }}"
      data-tabs="{{ data_tabs_enabled }}">
    </div>

    <div id="comparison-market-selector" class="p-v-l m-v-l" />

    <script>
      magna.CompareMarkets({
        element: document.querySelector("#open-product-finder"),
        cta_container: document.querySelector("#cta-container"),
        selectedTab:'POPULATION',
      })
      magna.SelectComparisonMarket({
        element: document.querySelector("#comparison-market-selector")
      })
    </script>
  {% else %}
    <div class="g-panel">
      <p>This section isn’t available yet</p>
      <p>This Beta version is limited</p>
    </div>
    <div class="m-v-xl">
        <button class="button button--tertiary" disabled>Coming soon</button>
    </div>
  {% endif %}
{% endblock %}

core/templates/core/exportplanstart.html
{% load static from staticfiles %}
{% block head_title %}Export Plan - great.gov.uk{% endblock %}
{% block tab_content %}
    <div class="grid-row" id="tab-content">
        <div class="column-two-thirds">
            <section id="welcome-message">
                <h2 class="heading-large margin-top-60 margin-bottom-30">Your Export Plan</h2>
                <p class="body-text margin-bottom-0">Product/Country</p>
                <div id="business-details-edit-form">
                    <form method="get" enctype="multipart/form-data">
                        {% block form %}
                        {{ form }}
                        {% endblock %}
                        {% block form_button %}
                            <button class="button margin-top-30">Get Rules & Regs</button>
                        {% endblock %}
                        <div>
                            <br>
                            <br>
                        </div>
                     </form>
                </div>
                {% if rules_regulation %}
                <table border="1">
                     <thead>
                      <tr>
                          {% for key,value in rules_regulation.items %}
                            <th class="border-light-grey padding-top-15 padding-bottom-15" scope="col">{{ key }}</th>
                          {% endfor %}
                      </tr>
                    </thead>
                    <tbody>
                    <tr>
                         {% for key,value in rules_regulation.items %}
                        <td class="border-white padding-top-15 padding-bottom-10">{{ value }}</td>
                        {% endfor %}
                    </tr>
                    </tbody>
                </table>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <button type="submit">Create Export Plan</button>
                </form>
                {% endif %}
            </section>

        </div>
    </div>
{% endblock tab_content %}

core/templates/core/generic_page.html
{% extends "core/base.html" %}
{% load wagtailimages_tags %}
{% load wagtailcore_tags %}
{% load static %}

{% block content %}

<section class="main-section bg-black-10 {{ view.slug }}-content" id="{{ view.slug }}-content">
  <section class="container">
    <div class="grid">
      <div class="c-1-3">&nbsp;</div>
      <div class="c-1-2 p-t-xl p-b-s">
        <h1 class="h-xl">{{ page.title }}</h1>
        <p>{{ page.description | richtext }}</p>
        {% include_block page.button %}
      </div>
    </div>
  </section>
  {% if page.image %}
    <div class="c-full">
      {% image page.image max-1600x600 class="m-f-auto m-r-auto" %}
    </div>
  {% endif %}
  <section class="container">
    {{ page.body}}
  </section>
</section>
{{ page.components }}

{% endblock %}

core/templates/core/personalised_page_struct_block.html
{{ block.value.paragraph }}

core/templates/core/struct_video_block.html
{% load video_tags %}

{% render_video block.value.video %}